export const galleryData = [
  {
    name: 'cricket',
    label: 'Cricket',
    image: 'https://images.unsplash.com/photo-1540747913346-19212a4b74a5?auto=format&fit=crop&w=800&q=80',
    description: 'An electrifying cricket event that packed the stadium to full capacity. Fans erupted in cheer as boundaries were hit for fun. The atmosphere was absolutely electric as two rival teams clashed for supremacy in a nail-biting final over showdown. The crowd roared with every wicket and six, making it a match that no spectator will forget.',
    timeline: [
      { time: '1:00 PM', event: 'Gates Open & Fan Zone Begins' },
      { time: '2:00 PM', event: 'Toss Ceremony & Team Introductions' },
      { time: '2:30 PM', event: 'Match Commences — 1st Innings' },
      { time: '5:30 PM', event: 'Strategic Break & Halftime Show' },
      { time: '6:00 PM', event: '2nd Innings Begins' },
      { time: '9:00 PM', event: 'Final Over — Crowd on its Feet' },
      { time: '9:45 PM', event: 'Trophy Presentation & Closing Ceremony' },
    ],
  },
  {
    name: 'office-party',
    label: 'Office Party',
    image: 'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=800&q=80',
    description: 'Our annual office party was an absolute blast! The entire team came together to celebrate a successful year of growth, milestones, and teamwork. From amazing food spreads to surprise awards and dance floors going until midnight, the party truly captured the spirit of our incredible workplace culture.',
    timeline: [
      { time: '6:00 PM', event: 'Venue Opens & Welcome Drinks' },
      { time: '6:30 PM', event: 'CEO Welcome Speech & Year Review' },
      { time: '7:00 PM', event: 'Buffet Dinner & Networking' },
      { time: '8:30 PM', event: 'Employee Awards & Recognition' },
      { time: '9:00 PM', event: 'DJ Night Begins — Dance Floor Opens' },
      { time: '11:00 PM', event: 'Special Surprise Performance' },
      { time: '12:00 AM', event: 'Midnight Countdown & Farewell' },
    ],
  },
  {
    name: 'december-events',
    label: 'December Events',
    image: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=800&q=80',
    description: 'December brought a magical season of events packed with festivities, food, and cheer. We hosted multiple back-to-back events across the city, each more spectacular than the last. From Christmas parties to New Year countdowns, every gathering was a vibrant celebration of community and spirit.',
    timeline: [
      { time: 'Dec 1', event: 'Season Kickoff — Winter Carnival' },
      { time: 'Dec 14', event: 'Charity Fundraiser Gala' },
      { time: 'Dec 21', event: 'Winter Solstice Music Night' },
      { time: 'Dec 25', event: 'Grand Christmas Celebration' },
      { time: 'Dec 28', event: 'Year-In-Review Networking Event' },
      { time: 'Dec 31', event: 'New Year Countdown Party — Midnight Fireworks' },
    ],
  },
  {
    name: 'food-zone',
    label: 'Food Zone',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
    description: 'The Food Zone event was a sensory paradise for every food lover. Curated stalls from over 40 vendors sprawled across a massive venue, offering cuisines from across India and the globe. Celebrity chefs demonstrated live cooking techniques while guests sampled exotic flavours, artisan desserts, and craft beverages.',
    timeline: [
      { time: '11:00 AM', event: 'Gates Open — Food Stalls Live' },
      { time: '12:00 PM', event: 'Celebrity Chef Live Cooking Demo' },
      { time: '1:00 PM', event: 'Eating Challenge Competition' },
      { time: '3:00 PM', event: 'World Cuisine Tasting Tour' },
      { time: '5:00 PM', event: 'Dessert & Drinks Festival' },
      { time: '7:00 PM', event: 'Best Stall Awards Announced' },
      { time: '8:30 PM', event: 'Closing & Grand Raffle Draw' },
    ],
  },
  {
    name: 'garba',
    label: 'Garba Night',
    image: 'https://media.istockphoto.com/id/2195664068/photo/india-navratri-festival-in-baroda-gujarat.jpg?s=612x612&w=0&k=20&c=EIDCjLJK9f_UcMuwsv-Ga0HDHQiKiBAvJUraP5mU8N0=',
    description: 'Garba Night was a breathtaking spectacle of tradition, colour, and rhythm. Thousands arrived dressed in vibrant chaniya cholis and kediyas, transforming the grounds into a living canvas of festive culture. The traditional Garba circles moved in perfect synchrony under strings of decorative lights, creating a scene that moved everyone to tears of joy.',
    timeline: [
      { time: '7:00 PM', event: 'Venue Opens — Welcome Ceremony' },
      { time: '7:30 PM', event: 'Entry of Chief Guests & Inauguration' },
      { time: '8:00 PM', event: 'First Circle of Garba Begins' },
      { time: '9:00 PM', event: 'Live Folk Music Performance Peaks' },
      { time: '10:00 PM', event: 'Competition Rounds — Prize Garba' },
      { time: '11:00 PM', event: 'Champion Circle Award Announcement' },
      { time: '11:30 PM', event: 'Grand Aarti & Cultural Closing' },
    ],
  },
  {
    name: 'concert',
    label: 'Concert Night',
    image: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=800&q=80',
    description: 'The concert was a thunderous, unforgettable night packed with raw energy and musical mastery. World-class performers took the stage to thousands of screaming fans, delivering an electrifying set of anthems and new releases. Light rigs, pyrotechnics, and a flawless sound system elevated the performance to legendary status.',
    timeline: [
      { time: '5:00 PM', event: 'Venue Gates Open' },
      { time: '6:30 PM', event: 'Opening Act — Emerging Bands' },
      { time: '8:00 PM', event: 'Main Stage — Headline Artist Enters' },
      { time: '9:00 PM', event: 'Peak Performance — Crowd Singalong' },
      { time: '10:00 PM', event: 'Special Guest Collaboration' },
      { time: '10:45 PM', event: 'Encore — Fan Favourite Tracks' },
      { time: '11:30 PM', event: 'Closing Act & Artist Meet & Greet' },
    ],
  },
];
